{{ config(materialized="table") }}

SELECT
    ORDER_ID
  , COALESCE(STORE_ID, 0) AS STORE_ID
  , COALESCE(CHANNEL_ID, 0) AS CHANNEL_ID
  , PAYMENT_ORDER_ID
  , DELIVERY_ORDER_ID
  , UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS
  , COALESCE(ORDER_AMOUNT, 0) AS ORDER_AMOUNT
  , COALESCE(ORDER_DELIVERY_FEE, 0) AS ORDER_DELIVERY_FEE
  , COALESCE(ORDER_DELIVERY_COST, 0) AS ORDER_DELIVERY_COST
  , ORDER_CREATED_HOUR
  , ORDER_CREATED_MINUTE
  , ORDER_CREATED_DAY
  , ORDER_CREATED_MONTH
  , ORDER_CREATED_YEAR
  , ORDER_MOMENT_CREATED
  , ORDER_MOMENT_ACCEPTED
  , ORDER_MOMENT_READY
  , ORDER_MOMENT_COLLECTED
  , ORDER_MOMENT_IN_EXPEDITION
  , ORDER_MOMENT_DELIVERING
  , ORDER_MOMENT_DELIVERED
  , ORDER_MOMENT_FINISHED
  , ORDER_METRIC_COLLECTED_TIME
  , ORDER_METRIC_PAUSED_TIME
  , ORDER_METRIC_PRODUCTION_TIME
  , ORDER_METRIC_WALKING_TIME
  , ORDER_METRIC_EXPEDITON_SPEED_TIME
  , ORDER_METRIC_TRANSIT_TIME
  , ORDER_METRIC_CYCLE_TIME
FROM {{ source('delivery_center', 'orders') }}
WHERE ORDER_ID IS NOT NULL