{{ config(materialized="table") }}

WITH payment_methods AS (
    SELECT
        PAYMENT_ORDER_ID
      , LISTAGG(DISTINCT PAYMENT_METHOD, ', ') WITHIN GROUP ( ORDER BY PAYMENT_METHOD) AS PAYMENT_METHODS
    FROM {{ ref('payments') }}
    GROUP BY 1
)
, deliveries AS (
    SELECT *
    FROM {{ ref('deliveries') }}
    QUALIFY ROW_NUMBER() OVER(PARTITION BY DELIVERY_ORDER_ID ORDER BY DELIVERY_ID DESC) = 1
)
SELECT
    TO_DATE(o.ORDER_MOMENT_CREATED) AS DATE
  , MONTHNAME(o.ORDER_MOMENT_CREATED) AS MONTH
  , SUBSTR(o.ORDER_MOMENT_CREATED::STRING, 1, 7) AS YEAR_MONTH
  , DAYNAME(o.ORDER_MOMENT_CREATED) AS DAY
  , HOUR(o.ORDER_MOMENT_CREATED) AS HOUR
  , o.ORDER_ID
  , o.ORDER_STATUS
  , REPLACE(c.CHANNEL_NAME, 'PLACE', '') AS CHANNEL_NAME
  , UPPER(TRIM(s.STORE_NAME)) AS STORE_NAME
  , IFF(s.STORE_LATITUDE = 0, NULL, s.STORE_LATITUDE) AS STORE_LATITUDE
  , IFF(s.STORE_LONGITUDE = 0, NULL, s.STORE_LONGITUDE) AS STORE_LONGITUDE
  , h.HUB_NAME
  , h.HUB_CITY
  , s.STORE_SEGMENT
  , o.ORDER_AMOUNT
  , o.ORDER_DELIVERY_COST
  , o.ORDER_DELIVERY_FEE
  , (o.ORDER_AMOUNT + o.ORDER_DELIVERY_COST + o.ORDER_DELIVERY_FEE) AS ORDER_TOTAL_AMOUNT
  , COALESCE(m.PAYMENT_METHODS, 'None') AS PAYMENT_METHODS
  , dri.DRIVER_MODAL AS DRIVER_TYPE
  , ROUND(d.DELIVERY_DISTANCE_METERS / 1000, 2) AS DISTANCE_KM
  , o.ORDER_METRIC_COLLECTED_TIME
  , o.ORDER_METRIC_PAUSED_TIME
  , o.ORDER_METRIC_PRODUCTION_TIME
  , o.ORDER_METRIC_WALKING_TIME
  , o.ORDER_METRIC_EXPEDITON_SPEED_TIME
  , o.ORDER_METRIC_TRANSIT_TIME
  , o.ORDER_METRIC_CYCLE_TIME
FROM {{ ref('orders') }} o
    LEFT JOIN {{ ref('channels') }} c
            ON o.CHANNEL_ID = c.CHANNEL_ID
    LEFT JOIN {{ ref('stores') }} s
            ON o.STORE_ID = s.STORE_ID
    LEFT JOIN {{ ref('hubs') }} h
            ON h.HUB_ID = s.HUB_ID
    LEFT JOIN payment_methods m
            ON o.PAYMENT_ORDER_ID = m.PAYMENT_ORDER_ID
    LEFT JOIN deliveries d
            ON d.DELIVERY_ORDER_ID = o.ORDER_ID
    LEFT JOIN {{ ref('drivers') }} dri
            ON dri.DRIVER_ID = d.DRIVER_ID
